name: FreeBSD-build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    name: Build in FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: Build on FreeBSD
      uses: vmactions/freebsd-vm@v0.2.9
      id: build
      with:
        usesh: true
        prepare: |
          pkg install -y curl go

        run: |
          freebsd-version
          pwd
          ls -lah
          go build
          ls -lah
    - uses: actions/upload-artifact@v3
      with:
        name: ntp-freebsd13.1-latest
        path: ntp
